# MkDocs options.
# See: https://www.mkdocs.org/user-guide/configuration/
site_name: Coda Packs SDK
# TODO(spencer): Update with new url
site_url: !ENV [MK_DOCS_SITE_URL, "https://coda.io/developers/temp-developer-docs/packs/"]
repo_url: https://github.com/coda/packs-sdk
edit_uri: https://github.com/coda/packs-sdk/blob/main/docs
docs_dir: docs
extra_css:
  - assets/custom.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  # Snippets inclusion.
  # See: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.snippets:
      base_path:
        - documentation
        - docs
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
      # Don't show TOC entries for h4 and below, as it clutters the TOC in the reference docs.
      toc_depth: 1-3
plugins:
    - search
    # Navigation enhancements.
    # See: https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
    - awesome-pages:
        filename: .nav.yml
    # Variables in markdown.
    # See: https://squidfunk.github.io/mkdocs-material/reference/variables/
    - macros

# Material theme options.
# See: https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: documentation/theme
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate
  palette:
    scheme: coda
  logo: assets/logo.png
  favicon: assets/favicon.png
