# MkDocs options.
# See: https://www.mkdocs.org/user-guide/configuration/
site_name: Coda Pack SDK
site_description: "Documentation for the SDK to build Coda Packs."
site_url: !ENV [MK_DOCS_SITE_URL, "https://coda.io/packs/build/latest/"]
repo_url: https://github.com/coda/packs-sdk
repo_name: coda/packs-sdk
edit_uri: edit/main/docs
docs_dir: docs
extra_css:
  - assets/custom.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  # Snippets inclusion.
  # See: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.snippets:
      base_path:
        - documentation
        - docs
        - .
      check_paths: true
      auto_append:
        - .abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      # Don't show TOC entries for h4 and below, as it clutters the TOC in the reference docs.
      toc_depth: 1-3

plugins:
    - search
    # Navigation enhancements.
    # See: https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
    - awesome-pages:
        filename: .nav.yml
    # Variables in markdown.
    # See: https://squidfunk.github.io/mkdocs-material/reference/variables/
    - macros
    - redirects:
        redirect_maps:
          # 2022-01-14: Reorganize guides and tutorials.
          "guides/advanced/autocomplete.md": "guides/basics/parameters/autocomplete.md"
          "guides/advanced/dynamic-sync-tables.md": "guides/blocks/sync-tables/dynamic.md"
          "guides/advanced/cli.md": "guides/development/cli.md"
          "guides/advanced/libraries.md": "guides/development/libraries.md"
          "guides/advanced/testing.md": "guides/development/testing.md"
          "guides/troubleshooting.md": "guides/development/troubleshooting.md"
          "get-started/cli.md": "tutorials/get-started/cli.md"
          "get-started/web.md": "tutorials/get-started/web.md"
          # 2022-09-08: Move some guides from advanced to basic.
          "guides/advanced/authentication/index.md": "guides/basics/authentication/index.md"
          "guides/advanced/authentication/oauth2.md": "guides/basics/authentication/oauth2.md"
          "guides/advanced/fetcher.md": "guides/basics/fetcher.md"
          # 2022-09-14: Move Overview page.
          "guides/index.md": "guides/overview.md"
          # 2023-01-05: Move FAQ and Changelog to Support.
          "guides/faq.md": "support/faq.md"
          "reference/changes.md": "support/changes.md"
          # 2023-05-01: Rename Webinars to Videos.
          "tutorials/webinars.md": "tutorials/videos.md"
          # 2023-10-02: Launch two-way sync.
          "guides/advanced/two-way-sync.md": "guides/blocks/sync-tables/two-way.md"
    # Run Python scripts during the MkDocs generation process.
    - mkdocs-simple-hooks:
        hooks:
          on_page_markdown: "documentation.scripts.mkdocs_hooks:on_page_markdown"
    # Generate card images for social sharing.
    - social:
        cards: !ENV [MK_DOCS_GENERATE_CARDS, true]
        cards_layout_options:
          background_color: "#006838"  # Emerald
          color: "#FFFFFF"


extra:
  # Social icons for the footer.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/coda_hq
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC73YRwUcAjAW_euaGzDUAzg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codainc/mycompany/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/codahq/

  # Custom variables.
  coda:
    pack_panel_clicks: "**Insert** > **Packs** > **{Pack name}**"

# Copyright that appears in the footer.
copyright: "Copyright Â© 2022 Coda. All rights reserved."

# Material theme options.
# See: https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: documentation/theme
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    scheme: coda
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
